---
- hosts: localhost
  gather_facts: no
  vars:
    loopList:
      - foo
      - 1, 2, 3 4, 5
      - record, judge, next, credit
  tasks:
    - debug:
        msg: "Stirng {{ item }}"
      loop: "{{ loopList }}"
    - debug:
        msg: "Numbers {{ item }}!"
      loop: "{{ loopList }}"
    - debug:
        msg: "List {{ item }}!"
      loop: "{{ loopList }}"      
